server:
  port: 7004
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/marcklinux/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service
              
          
